{% set name = "git-town" %}
{% set version = "21.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/git-town/git-town/archive/v{{ version }}.tar.gz
  sha256: 428b388f0adb765b5cb4cbb4e9c5d210fe83d1e82c241ac9b076b4bbd5bdde99

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - git-town --help

about:
  home: https://github.com/git-town/git-town
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: High-level command-line interface for Git
  dev_url: https://github.com/git-town/git-town

extra:
  recipe-maintainers:
    - danielnachun
