{% set name = "git-town" %}
{% set version = "16.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/git-town/git-town/archive/v{{ version }}.tar.gz
  sha256: 99a50ad8c3713c86304f3858facc1e7ed20ae7077e4c9d8b4a324b7c62b97c5d

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - git-town --help

about:
  home: https://github.com/git-town/git-town
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: High-level command-line interface for Git
  dev_url: https://github.com/git-town/git-town

extra:
  recipe-maintainers:
    - danielnachun
