schema_version: 1

context:
  version: "23.0.1"

package:
  name: git-town
  version: ${{ version }}

source:
  url: https://github.com/git-town/git-town/archive/v${{ version }}.tar.gz
  sha256: 88f4cb8949a04ee0e8f4bc1e207568b0969e7094e62ab1e95c8562e0c7c84408

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - git-town --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: High-level command-line interface for Git
  homepage: https://github.com/git-town/git-town
  repository: https://github.com/git-town/git-town

extra:
  recipe-maintainers:
    - danielnachun
