schema_version: 1

context:
  version: "22.7.1"

package:
  name: git-town
  version: ${{ version }}

source:
  url: https://github.com/git-town/git-town/archive/v${{ version }}.tar.gz
  sha256: 1d7f136d5b932593281614f7a5ae2fbb8cf219233efe43022a9f93241c926478

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - git-town --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: High-level command-line interface for Git
  homepage: https://github.com/git-town/git-town
  repository: https://github.com/git-town/git-town

extra:
  recipe-maintainers:
    - danielnachun
