schema_version: 1

context:
  version: "24.1.0"

package:
  name: git-town
  version: ${{ version }}

source:
  url: https://github.com/git-town/git-town/archive/v${{ version }}.tar.gz
  sha256: 2a6fab5645dab15237a9b40f5c6c413dadfdd0e3fa5897f2f0dd10232fd9faea

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - git-town --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: High-level command-line interface for Git
  homepage: https://github.com/git-town/git-town
  repository: https://github.com/git-town/git-town

extra:
  recipe-maintainers:
    - danielnachun
